### ISSUE TITLE
YoutubeExplode.DemoConsole using .NET Core Command Line Tool (2.1.519), (3.1.404) and .NET Command Line Tool (5.0.101) not working

### ISSUE THREAD

**Issue by ohenley** [Tyrrrz/YoutubeExplode#496]
Hi,

If I go to the YoutubeExplode.DemoConsole folder (netcore2.1.519 installed on my system) and run 
```
dotnet run
```
I get a bunch of errors. They all look related to YoutubeExplode using language sugar/constructs not supported by netcore2.1. E.g.

```
ReverseEngineering\Responses\PlayerResponse.cs(275,73): error CS8124: Tuple must contain at least two elements. 
Channels\ChannelId.cs(98,81): error CS8124: Tuple must contain at least two elements. 
Internal\Html.cs(8,61): error CS8124: Tuple must contain at least two elements. 
ReverseEngineering\Responses\PlayerResponse.cs(275,73): error CS1026: ) expected 
Internal\Html.cs(8,62): error CS1526: A new expression requires (), [], or {} after type 
Internal\Extensions\AsyncEnumerableExtensions.cs(12,19): error CS1525: Invalid expression term 'foreach' 
...
```

You state it works with netcore2.0+ so am I missing something?

Thank you

**Comment by ohenley** [comment]
Just installed netcore5.0 and it fails again for different reasons. E.g.
```
Channels\UserName.cs(36,17): error CS8602: Dereference of a possibly null reference. 
Videos\VideoId.cs(36,17): error CS8602: Dereference of a possibly null reference. 
Channels\ChannelId.cs(36,18): error CS8602: Dereference of a possibly null reference. 
Playlists\PlaylistId.cs(44,18): error CS8602: Dereference of a possibly null reference. 
\Streams\StreamClient.cs(39,55): error CS8604: Possible null reference argument for parameter 'input' in 'string CipherOperationExtensions.Decipher(IEnumerable<ICipherOperation> operations, string input)'. 
...
```

**Comment by ohenley** [comment]
Just installed .NET Core SDK (3.1.404) and it fails again for different reasons. E.g.
```
Videos\VideoId.cs(106,68): error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. 
Internal\PooledBuffer.cs(19,57): error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. 
ReverseEngineering\Responses\PlayerResponse.cs(275,59): error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. 
Channels\ChannelId.cs(98,70): error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. 
...
```

**Comment by ohenley** [comment]
Ok,

It works using .NET Core SDK (3.1.404) if we add `<LangVersion>preview</LangVersion>` to the YoutubeExplode.csproj file like so:
```
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    ...
  </PropertyGroup>
```

**Comment by ohenley** [comment]
If I may, it would help to have a stricter readme, a tested config, and maybe a .NET branch and a .NET Core branch. (See maybe I do not understand the .NET ecosystem properly...)

IIRC, to run on Linux it needs to build against the .NET Core ... and as my experience/tests suggest we need to modify the .csproj(s) to make it fly for this path. For someone new or not really into the .NET ecosystem let say it is far from ideal.

Thx.

**Comment by Tyrrrz** [comment]
Hi @ohenley 
Sorry you had such a rough experience. Normally, it should work with just .NET 5.0 SDK.
That said, the issues you mentioned in [this comment](https://github.com/Tyrrrz/YoutubeExplode/issues/496#issuecomment-753002223) seem weird. I can't reproduce this locally, nor on [CI](https://github.com/Tyrrrz/YoutubeExplode/actions/runs/453642666) (which also runs .NET 5.0 SDK).

**Comment by ohenley** [comment]
Hi @Tyrrrz 
The rough experience started because I only have VS2017 on this machine.
About the .NET 5.0 SDK not working for me... maybe it is my bad, while I think about it I may have forgotten to properly set `<TargetFrameworks>` as I was brute-forcing my way at some point.

Thx for the feedback.
